# Generated by Django 4.1 on 2022-09-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_title_product_name_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
    ]
